import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{ArrowRight,ArrowLeft,Bot,Check,ChevronDown,ChevronLeft,ChevronRight,ClipboardList,FileText,GraduationCap,Image as ImageIcon,Laptop,Menu,MessageCircle,Phone,Send,Sparkles,UserRound,ShieldCheck,Clock3,Mail,UploadCloud,X,Settings2}from"lucide-react";
import"./styles.css";

const WA="923153400086",PHONE="03153400086",EMAIL="shoaibportfolio1@gmail.com";
const data={
 cv:{title:"CV / Resume",icon:FileText,price:500,desc:"Professional CV and resume design. Choose from 10 ready templates.",templates:["Modern Blue","Executive Gold","ATS Clean","Dark Professional","Minimal Classic","Corporate Split","Creative Portfolio","Elegant Resume","Fresh Graduate","One Page Pro"]},
 passport:{title:"Passport Size Photos",icon:UserRound,price:300,desc:"Professional passport-size photo editing for jobs, forms and applications.",templates:["Classic White","Blue Background","Clean Light","Job Photo","Formal Suit","Simple Passport","Studio Light","Professional ID","Application Photo","Premium Clean"]},
 job:{title:"Job Form Filling",icon:ClipboardList,price:200,desc:"Private and government job application form filling with careful review.",templates:["Govt Application","Private Job","Quick Apply","Career Form","Online Job","Professional Form","Simple Apply","Job Portal","Application Pro","Fast Form"]},
 "govt-account":{title:"Government Job Portal Account",icon:ShieldCheck,price:300,desc:"Help setting up a government job portal profile/account and application-ready information.",templates:["Portal Setup","Account Starter","Govt Profile","Job Seeker","Application Ready","Portal Pro","Career Account","Easy Login","Profile Plus","Govt Jobs"]},
 college:{title:"College / University Forms",icon:GraduationCap,price:200,desc:"College, university, admission and scholarship form support.",templates:["University Admission","College Form","Scholarship","Student Profile","Admission Pro","Simple Academic","Fresh Student","Online Admission","Education Plus","Campus Form"]},
 poster:{title:"Poster & Flyer Design",icon:ImageIcon,price:500,desc:"Professional posters and flyers for business, jobs, offers and social media.",templates:["Business Services","Special Offer","Job Announcement","Social Promo","Digital Flyer","Clean Corporate","Bold Sale","Service Menu","Modern Promo","Premium Flyer"]},
 windows:{title:"Windows Installation",icon:Laptop,price:800,desc:"Windows 10/11 installation, drivers and basic setup.",templates:["Windows 10","Windows 11","Pro Setup","Office PC","Home PC","Gaming Setup","Fast Install","Driver Setup","Full Setup","Fresh Windows"]},
 computer:{title:"Computer / Software Services",icon:Settings2,price:500,desc:"Software setup, computer support and basic troubleshooting.",templates:["Software Setup","PC Support","Laptop Care","Office Setup","Basic Repair","Speed Up","App Installation","System Care","Computer Pro","Tech Support"]}
};
const keys=Object.keys(data);

function scrollTop(){window.scrollTo({top:0,behavior:"smooth"})}
function go(hash){window.location.hash=hash;scrollTop()}

function Header({page,setPage}){const[m,setM]=useState(false);const links=[["Home","home"],["About","about"],["Services","services"],["Templates","templates"],["Jobs","latest-jobs"],["Pricing","pricing"],["Contact","contact"]];return <header className="nav"><a className="brand" onClick={()=>go("#home")}><span className="mark">S.S</span><span><b>S.S</b> Professional <em>Services</em><small>Serving Your Success</small></span></a><button className="hamb" onClick={()=>setM(!m)}>{m?<X/>:<Menu/>}</button><nav className={m?"open":""}>{links.map(([t,h])=><a className={page===h?"active":""} key={h} onClick={()=>{go("#"+h);setM(false)}}>{t}</a>)}<a className="support" href={`https://wa.me/${WA}`} target="_blank"><Phone size={16}/> Get Support</a></nav></header>}

function TemplateImage({kind,index}){return <img loading="lazy" src={`/templates/${kind}/${String(index+1).padStart(2,"0")}.svg`} alt={`${data[kind].templates[index]} template`}/>}

function OrderModal({order,setOrder}){const[o,setO]=useState(order||{});const[status,setStatus]=useState("");const submit=async e=>{e.preventDefault();setStatus("Sending...");try{const r=await fetch("/api/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(o)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not send");setStatus(`Sent successfully. Request ID: ${j.requestId}`)}catch(e){setStatus("Backend is not connected on this host yet. You can send the request directly on WhatsApp.");}};return <div className="modal-bg"><div className="modal"><button className="close" onClick={()=>setOrder(null)}><X/></button><span className="eyebrow">ORDER REQUEST</span><h2>Send your <b>choice</b></h2><p className="muted">We’ll receive your service and template selection.</p><form onSubmit={submit}><label>Name<input required value={o.name||""} onChange={e=>setO({...o,name:e.target.value})}/></label><label>Phone<input required value={o.phone||""} onChange={e=>setO({...o,phone:e.target.value})}/></label><label>Email (optional)<input type="email" value={o.email||""} onChange={e=>setO({...o,email:e.target.value})}/></label><div className="form-two"><label>Service<input readOnly value={o.service||""}/></label><label>Template<input readOnly value={o.template||"Not selected"}/></label></div><label>Details / instructions<textarea value={o.details||""} onChange={e=>setO({...o,details:e.target.value})} placeholder="Write text, job link, photo requirements, changes, etc."/></label><button className="btn primary full" type="submit"><Send size={17}/> Send Order</button></form>{status&&<div className="status">{status}</div>}<a className="wa-direct" href={`https://wa.me/${WA}?text=${encodeURIComponent(`Hi, I want ${o.service||"a service"}${o.template?` — Template: ${o.template}`:""}. My name is ${o.name||""}.`)}`} target="_blank"><MessageCircle size={16}/> Send directly on WhatsApp</a></div></div>}

function Home({setOrder}){return <><section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles size={15}/> DIGITAL • FAST • RELIABLE</span><h1>Smart Solutions<br/><span>for a Better Tomorrow</span></h1><p>CVs, passport photos, job forms, government job portal accounts, college forms, posters, Windows and computer services.</p><div className="hero-actions"><a className="btn primary" onClick={()=>go("#services")}>Get Started <ArrowRight/></a><a className="btn ghost" onClick={()=>go("#templates")}><ImageIcon/> Browse Templates</a></div><div className="hero-trust"><span><Check/> Fast service</span><span><ShieldCheck/> Reliable support</span><span><Clock3/> Online orders</span></div></div><div className="hero-visual"><div className="orb"></div><div className="mock-laptop"><div className="screen"><span className="win">⊞</span><div className="screen-lines"></div></div><div className="base"></div></div><div className="hero-card"><b>10+ templates</b><small>Choose your favorite</small></div></div></section><section className="section" id="services"><Title kicker="WHAT WE DO" title="Our" bold="Services" sub="Select a service to open its dedicated page and 10 templates."/><div className="service-grid">{keys.map(k=><ServiceCard key={k} k={k}/>)}</div></section><JobBoard/><section className="blue-strip"><div><span className="eyebrow">CUSTOMER CHOICE</span><h2>Pick your service. Pick your design. <b>Tell us what you need.</b></h2></div><button className="btn primary" onClick={()=>go("#templates")}>Explore Templates <ArrowRight/></button></section><section className="section"><Title kicker="SIMPLE PROCESS" title="From Choice to" bold="Done" sub="A clear online workflow for every service."/><Process/></section></>}

function Title({kicker,title,bold,sub}){return <div className="section-title"><span>{kicker}</span><h2>{title} <b>{bold}</b></h2>{sub&&<p>{sub}</p>}</div>}
function ServiceCard({k}){const s=data[k],I=s.icon;return <article className="service-card" onClick={()=>go("#service/"+k)}><div className="icon"><I/></div><h3>{s.title}</h3><p>{s.desc}</p><div className="card-foot"><b>From Rs. {s.price.toLocaleString()}</b><ArrowRight/></div></article>}
function Process(){return <div className="steps">{[["01","Choose service","Open any service page."],["02","Choose template","Select 1 of 10 designs."],["03","Send details","Tell us your exact requirements."],["04","Get support","We contact you and confirm the order."]].map(x=><div className="step" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div>}

function About(){return <><section className="page-hero"><span className="eyebrow">ABOUT S.S</span><h1>Professional help for your <b>digital work.</b></h1><p>One simple place for documents, applications, creative designs and computer services.</p></section><section className="section about-grid"><div><Title kicker="WHY CHOOSE US" title="Simple process." bold="Professional results."/><div className="checks">{["Professional & reliable work","Clear starting prices","Template choice before ordering","WhatsApp + online support","Careful form review"].map(x=><div key={x}><Check/>{x}</div>)}</div></div><div className="about-panel"><div><strong>500+</strong><span>Happy clients</span></div><div><strong>1000+</strong><span>Projects</span></div><div><strong>24/7</strong><span>Online support</span></div><div><strong>100%</strong><span>Customer focus</span></div></div></section></>}

function Templates({setOrder}){return <><section className="page-hero"><span className="eyebrow">TEMPLATE GALLERY</span><h1>Choose from <b>80 templates.</b></h1><p>Every service has 10 visual template choices.</p></section><section className="section"><div className="all-template-groups">{keys.map(k=><div className="template-group" key={k}><div className="group-head"><div><span>{data[k].title}</span><h2>10 templates</h2></div><button className="btn ghost-blue" onClick={()=>go("#service/"+k)}>Open service <ArrowRight/></button></div><div className="template-grid">{data[k].templates.map((t,i)=><article className="template-card" key={t}><TemplateImage kind={k} index={i}/><div><b>{t}</b><button onClick={()=>setOrder({service:data[k].title,template:t})}>Choose</button></div></article>)}</div></div>)}</div></section></>}

function ServicePage({kind,setOrder}){const s=data[kind],I=s.icon;return <><section className="page-hero service-page-hero"><div className="service-symbol"><I/></div><span className="eyebrow">SERVICE</span><h1>{s.title}</h1><p>{s.desc}</p><strong className="big-price">Starting from Rs. {s.price.toLocaleString()}</strong></section><section className="section"><div className="service-detail-top"><div><Title kicker="YOUR OPTIONS" title="Select a" bold="Template" sub={`10 designs available for ${s.title}.`}/></div><div className="note"><ShieldCheck/> Template choice is included in your order request.</div></div><div className="template-grid large">{s.templates.map((t,i)=><article className="template-card" key={t}><TemplateImage kind={kind} index={i}/><div><b>{t}</b><button onClick={()=>setOrder({service:s.title,template:t})}>Choose this <ArrowRight/></button></div></article>)}</div><div className="order-banner"><div><span>DON'T SEE EXACTLY WHAT YOU WANT?</span><h2>Tell us the changes you need.</h2></div><button className="btn primary" onClick={()=>setOrder({service:s.title,template:"Custom / Not selected"})}>Request custom design <ArrowRight/></button></div></section></>}

function Pricing(){return <><section className="page-hero"><span className="eyebrow">PRICING</span><h1>Normal, clear <b>starting prices.</b></h1><p>Final price can vary with complexity and extra work.</p></section><section className="section"><div className="price-grid">{keys.map(k=><div className="price-card" key={k}><div className="price-icon">{React.createElement(data[k].icon)}</div><h3>{data[k].title}</h3><strong>Rs. {data[k].price.toLocaleString()}</strong><p>Starting price</p><button onClick={()=>go("#service/"+k)}>View service <ArrowRight/></button></div>)}</div></section></>}

function Contact(){return <><section className="page-hero"><span className="eyebrow">CONTACT</span><h1>Let’s get your <b>work started.</b></h1><p>Contact S.S Professional Services for a quote or service request.</p></section><section className="section contact-grid"><div className="contact-card"><MessageCircle/><h3>WhatsApp</h3><p>Fastest way to send your service choice and details.</p><a className="btn primary" href={`https://wa.me/${WA}`} target="_blank">Chat on WhatsApp</a></div><div className="contact-card"><Phone/><h3>Phone</h3><p>{PHONE}</p><a className="btn ghost-blue" href={`tel:${PHONE}`}>Call Now</a></div><div className="contact-card"><Mail/><h3>Email</h3><p>{EMAIL}</p><a className="btn ghost-blue" href={`mailto:${EMAIL}`}>Send Email</a></div></section></>}

function Chat(){const[open,setOpen]=useState(false),[msg,setMsg]=useState(""),[messages,setMessages]=useState([{from:"bot",t:"Hi 👋 I’m the S.S assistant. Ask about CVs, passport photos, job forms, government job portal accounts, posters, college forms or Windows."}]);function send(){if(!msg.trim())return;const q=msg.trim(),l=q.toLowerCase();setMessages(m=>[...m,{from:"user",t:q}]);let a="Choose a service and template. Starting prices are shown on each service page.";if(l.includes("cv")||l.includes("resume"))a="CV/Resume starts from Rs. 500 and has 10 templates.";else if(l.includes("passport"))a="Passport-size photo editing starts from Rs. 300 and has 10 templates.";else if(l.includes("govt")||l.includes("government"))a="Government job portal account help starts from Rs. 300. We can guide you through the profile setup.";else if(l.includes("job form"))a="Job form filling starts from Rs. 200 per application.";else if(l.includes("poster"))a="Poster/Flyer design starts from Rs. 500.";else if(l.includes("windows"))a="Windows installation starts from Rs. 800.";setTimeout(()=>setMessages(m=>[...m,{from:"bot",t:a}]),250);setMsg("")}return <>{open&&<div className="chat"><div className="chat-head"><Bot/><div><b>S.S AI Assistant</b><small>Free front-end assistant</small></div><button onClick={()=>setOpen(false)}><X/></button></div><div className="chat-body">{messages.map((m,i)=><div key={i} className={"bubble "+m.from}>{m.t}</div>)}</div><div className="chat-input"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask a question..."/><button onClick={send}><Send/></button></div></div>}<button className="chat-fab" onClick={()=>setOpen(!open)}>{open?<X/>:<><Bot/><span>AI Help</span></>}</button></>}


function JobBoard(){
  const[jobs,setJobs]=useState([]),[loading,setLoading]=useState(true),[filter,setFilter]=useState("All");
  useEffect(()=>{fetch("/api/jobs").then(r=>r.json()).then(j=>setJobs(j.jobs||[])).catch(()=>setJobs([])).finally(()=>setLoading(false))},[]);
  const shown=jobs.filter(j=>filter==="All"||j.type===filter);
  return <section className="job-board section" id="latest-jobs">
    <div className="job-board-head"><div><span className="eyebrow dark">LATEST JOB ALERTS</span><h2>New <b>Government & Private Jobs</b></h2><p>Verified-source job links can appear here automatically when a connected feed is updated.</p></div>
      <div className="job-filters">{["All","Government","Private"].map(x=><button className={filter===x?"selected":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div>
    </div>
    {loading?<div className="jobs-loading">Checking latest job sources…</div>:<div className="job-grid">{shown.map(j=><article className="job-card" key={j.id}><div className="job-top"><span className={"job-tag "+(j.type==="Government"?"gov":"private")}>{j.type}</span><small>{j.posted}</small></div><h3>{j.title}</h3><p>{j.company} • {j.location}</p><div className="job-meta"><span>Deadline: {j.deadline}</span><a href={j.applyUrl} target="_blank" rel="noreferrer">View / Apply <ArrowRight/></a></div><small className="source">Source: {j.source}</small></article>)}</div>}
    <div className="job-note"><ShieldCheck/> <span>For government jobs, the site should always link candidates to the official advertisement/application source. The FPSC explicitly says its official website is the primary source for candidates. citeturn0search0</span></div>
  </section>
}

function Footer(){return <footer><div className="footer-grid"><a className="brand"><span className="mark">S.S</span><span><b>S.S</b> Professional <em>Services</em><small>Serving Your Success</small></span></a><div><b>Services</b>{keys.slice(0,5).map(k=><a key={k} onClick={()=>go("#service/"+k)}>{data[k].title}</a>)}</div><div><b>Contact</b><a href={`https://wa.me/${WA}`}>WhatsApp: {PHONE}</a><a href={`mailto:${EMAIL}`}>{EMAIL}</a></div></div><div className="copyright">© 2026 S.S Professional Services. All Rights Reserved.</div></footer>}

function App(){const[hash,setHash]=useState(location.hash||"#home"),[order,setOrder]=useState(null);useEffect(()=>{const f=()=>setHash(location.hash||"#home");addEventListener("hashchange",f);return()=>removeEventListener("hashchange",f)},[]);const path=hash.replace("#","");let page;if(path.startsWith("service/"))page=<ServicePage kind={path.split("/")[1]} setOrder={setOrder}/>;else if(path==="about")page=<About/>;else if(path==="services")page=<><section className="page-hero"><span className="eyebrow">ALL SERVICES</span><h1>Every service has its <b>own page.</b></h1><p>Select a service to see pricing and 10 templates.</p></section><section className="section"><div className="service-grid">{keys.map(k=><ServiceCard key={k} k={k}/>)}</div></section></>;else if(path==="templates")page=<Templates setOrder={setOrder}/>;else if(path==="latest-jobs")page=<><JobBoard/></>;else if(path==="pricing")page=<Pricing/>;else if(path==="contact")page=<Contact/>;else page=<Home setOrder={setOrder}/>;const current=path.startsWith("service/")?"services":path;return <><Header page={current}/><main>{page}</main><Footer/><Chat/>{order&&<OrderModal order={order} setOrder={setOrder}/>}</>}
createRoot(document.getElementById("root")).render(<App/>);
